### ISSUE TITLE
I don't handle the protocol ' dropbox ' 

### ISSUE THREAD

**Issue by jonpolak** [anishathalye/git-remote-dropbox#35] opened 2016-04-28 22:00 UTC
Sometimes it pushes without an issue. sometimes it tells me that it doesn't know what to do with dropbox://

i installed it in a virtualenv 
`virtualenv -p python3 git-remote-dropbox`
`cd git-remote-dropbox`
`pip install git-remote-dropbox`
`source ./bin/activate`

`git add remote origin "dropbox://repos/project1"`
`git push origin master`

**Comment by anishathalye** [comment] 2016-04-29 01:00
Just curious - why are you installing a system tool in a virtualenv?

Also, can you provide more information on how to reproduce the issue?

**Comment by jonpolak** [comment] 2016-05-01 05:13
Well when git-remote-dropbox works is phenomenal. Better than using git
repo like bitbucket because can instantiate new repo from CLI.

I don't have a good answer as to why virtual environment - it's mostly a
force of habit and a way to avoid installing with sudo.

How to replicate... It happens when you type

`git push newOrigin master`

When newOrigin was defined with
`git remote set-url --add newOrigin dropbox://`

**Comment by anishathalye** [comment] 2016-05-01 21:21
Oh hmm I've never used the `--add` switch on `set-url` before. What's the reason for having multiple URLs associated with a single remote as opposed to having multiple remotes each with one URL?

**Comment by jonpolak** [comment] 2016-05-02 14:08
Yes. Say you already had a project that you were syncing with github. Then
you want to push to Dropbox as well. But you don't want to lose the github
remote. So you add an additional URL to origin

**Comment by anishathalye** [comment] 2016-05-02 14:12
Hm, but why not `git remote add dropbox dropbox://path/to/repo`? Then you can `git push origin master` or `git push dropbox master`.

**Comment by jonpolak** [comment] 2016-05-02 16:20
I wanted to have both remote repos sync with a single git push
see here:
http://stackoverflow.com/questions/14290113/git-pushing-code-to-two-remotes

**Comment by jonpolak** [comment] 2016-05-02 17:26
btw - I haven't seen the error again in a while. it seems to occur on the first sync only.

**Comment by anishathalye** [comment] 2017-03-01 19:35
This issue is kinda old, so I'm gonna close this for now. If stuff is still broken, please reopen the issue.

Also, try running with `-v` to see if it gives you any more info when things are going wrong.

**Closed by anishathalye** 2017-03-01 19:35 UTC
Labels: needs-triage
