### ISSUE TITLE
Make it faster

### ISSUE THREAD

**Issue by sprig** [anishathalye/git-remote-dropbox#34] opened 2016-04-26 14:49 UTC
I do not have precise timing yet (will check and add some later), but subjectively, it seems that this remote is incomparably slower than e.g. ssh.

It would be great if it could be sped up. Are there specific known bottlenecks, e.g. uploading only one file at a time?

**Comment by anishathalye** [comment] 2016-04-26 17:33
Yup, it's pretty slow. I'm pretty sure it's the Dropbox API that's the cause of the problem, and I'm not sure how to make it faster.

At least when downloading, we need to make a lot of roundtrips to the server. When uploading, we just need to upload a bunch of stuff.

In either case, the program is already doing it in parallel.
Downloading: https://github.com/anishathalye/git-remote-dropbox/blob/master/git_remote_dropbox/__init__.py#L522
Uploading: https://github.com/anishathalye/git-remote-dropbox/blob/master/git_remote_dropbox/__init__.py#L424

**Comment by sprig** [comment] 2016-04-26 21:51
I think it might be possible achieve speed up by increasing the number of threads from the native CPU amount to something greater, or even to a large number of processes, since not only is the GIL released during the upload, but also the CPU time in general, if I'm not mistaken.

**Comment by anishathalye** [comment] 2016-04-26 22:11
We're already using 20 processes: https://github.com/anishathalye/git-remote-dropbox/blob/master/git_remote_dropbox/__init__.py#L41

Some time ago, I played around with changing the number. Increasing it didn't seem to help.

**Comment by sprig** [comment] 2016-04-27 00:17
Oh, that is unfortunate.

**Comment by anishathalye** [comment] 2019-02-05 03:41
Closing this because I think there's nothing we can do -- it's a function of the Dropbox API for Python.

**Closed by anishathalye** 2019-02-05 03:41 UTC
Labels: enhancement, medium-priority
