### ISSUE TITLE
Unexpected exception when pushing from windows

### ISSUE THREAD

**Issue by Vitruvia** [anishathalye/git-remote-dropbox#65] opened 2017-07-23 18:30 UTC
Hi, when I try to push to a repo on windows 7 64bits I get this:

`unexpected exception (run with -v for details)`

Running with -v gives:

```
Pushing to dropbox:///test
Traceback (most recent call last):
  File "p:\anaconda\lib\site-packages\urllib3\util\timeout.py", line 124, in _validate_timeout
    float(value)
TypeError: float() argument must be a string or a number, not 'Timeout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "p:\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "p:\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "P:\Anaconda\Scripts\git-remote-dropbox.exe\__main__.py", line 9, in <module>
  File "p:\anaconda\lib\site-packages\git_remote_dropbox\__init__.py", line 759, in main
    helper.run()
  File "p:\anaconda\lib\site-packages\git_remote_dropbox\__init__.py", line 370, in run
    self._do_list(line)
  File "p:\anaconda\lib\site-packages\git_remote_dropbox\__init__.py", line 395, in _do_list
    refs = self._get_refs(for_push=for_push)
  File "p:\anaconda\lib\site-packages\git_remote_dropbox\__init__.py", line 652, in _get_refs
    res = self._connection().files_list_folder(loc, recursive=True)
  File "p:\anaconda\lib\site-packages\dropbox\base.py", line 715, in files_list_folder
    None,
  File "p:\anaconda\lib\site-packages\dropbox\dropbox.py", line 234, in request
    timeout=timeout)
  File "p:\anaconda\lib\site-packages\dropbox\dropbox.py", line 325, in request_json_string_with_retry
    timeout=timeout)
  File "p:\anaconda\lib\site-packages\dropbox\dropbox.py", line 409, in request_json_string
    timeout=timeout,
  File "p:\anaconda\lib\site-packages\requests\sessions.py", line 565, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "p:\anaconda\lib\site-packages\requests\sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "p:\anaconda\lib\site-packages\requests\sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "p:\anaconda\lib\site-packages\requests\adapters.py", line 438, in send
    timeout=timeout
  File "p:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 588, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "p:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 303, in _get_timeout
    return Timeout.from_float(timeout)
  File "p:\anaconda\lib\site-packages\urllib3\util\timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "p:\anaconda\lib\site-packages\urllib3\util\timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "p:\anaconda\lib\site-packages\urllib3\util\timeout.py", line 127, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=30, read=30, total=None), but it must be an int, float or None.
```

The only steps that I have taken were installing the program via pip (as in the instructions) and creating a file called `.git-remote-dropbox.json` in my home folder (inside my user profile) with the API key, then creating a test repo in my computer (not in dropbox), then running `git remote add origin dropbox:///`.

What could I be doing wrong?

**Comment by anishathalye** [comment] 2017-07-24 07:23
That's strange. How did you install git-remote-dropbox?

**Comment by Vitruvia** [comment] 2017-07-24 11:42
`pip install git-remote-dropbox` just like in the readme. Maybe I should have used conda or pip3?
There is a git-remote-dropbox.exe in the same directory as my other scripts (Anaconda/Scripts) though...

**Comment by anishathalye** [comment] 2017-07-24 20:41
Well, in any case, it looks like the issue is coming from the [Dropbox Python SDK](https://github.com/dropbox/dropbox-sdk-python).

If it's not too much trouble, could you try running it with Python 3 instead of Python 2 (or the other way around, if you were using Python 3 before)?

Debugging Windows issues is a bit tough for me cause I don't really use Windows / don't currently have a Windows machine or VM.

**Comment by Vitruvia** [comment] 2017-07-25 00:58
Running it on a virtualenv with python2.7.8 gave me:

```
c:\users\thalesa\envs\test\lib\site-packages\urllib3\util\ssl_.py:339:
SNIMissin
gWarning: An HTTPS request has been made, but the SNI (Subject Name
Indication)
extension to TLS is not available on this platform. This may cause the
server to
present an incorrect TLS certificate, which can cause validation
failures. You
can upgrade to a newer version of Python to solve this. For more
information, se
e
https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
SNIMissingWarning
c:\users\thalesa\envs\test\lib\site-packages\urllib3\util\ssl_.py:137:
InsecureP
latformWarning: A true SSLContext object is not available. This
prevents urllib3
from configuring SSL appropriately and may cause certain SSL
connections to fai
l. You can upgrade to a newer version of Python to solve this. For
more informat
ion, see
https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnin
gs
  InsecurePlatformWarning
  c:\users\thalesa\envs\test\lib\site-packages\urllib3\util\ssl_.py:137:
  InsecureP
  latformWarning: A true SSLContext object is not available. This
  prevents urllib3
   from configuring SSL appropriately and may cause certain SSL
   connections to fai
   l. You can upgrade to a newer version of Python to solve this.
   For more informat
   ion, see
   https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnin
       gs
         InsecurePlatformWarning
         Everything up-to-date
```

**Comment by kylebarron** [comment] 2017-08-07 01:23
I'm running Ubuntu 16.04 and getting the same error. I did both `pip install git-remote-dropbox` and also `pip3 install git-remote-dropbox`, added the key to the json file, and tried to push a repo to dropbox with no success. 

```python
> git push dropbox master -v
Pushing to dropbox:///Apps/test-git/stata-autokey
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.6/site-packages/urllib3/util/timeout.py", line 124, in _validate_timeout
    float(value)
TypeError: float() argument must be a string or a number, not 'Timeout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda/bin/git-remote-dropbox", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 759, in main
    helper.run()
  File "/opt/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 370, in run
    self._do_list(line)
  File "/opt/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 395, in _do_list
    refs = self._get_refs(for_push=for_push)
  File "/opt/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 652, in _get_refs
    res = self._connection().files_list_folder(loc, recursive=True)
  File "/opt/anaconda/lib/python3.6/site-packages/dropbox/base.py", line 715, in files_list_folder
    None,
  File "/opt/anaconda/lib/python3.6/site-packages/dropbox/dropbox.py", line 234, in request
    timeout=timeout)
  File "/opt/anaconda/lib/python3.6/site-packages/dropbox/dropbox.py", line 325, in request_json_string_with_retry
    timeout=timeout)
  File "/opt/anaconda/lib/python3.6/site-packages/dropbox/dropbox.py", line 409, in request_json_string
    timeout=timeout,
  File "/opt/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/opt/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/opt/anaconda/lib/python3.6/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/opt/anaconda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 588, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/opt/anaconda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 303, in _get_timeout
    return Timeout.from_float(timeout)
  File "/opt/anaconda/lib/python3.6/site-packages/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/opt/anaconda/lib/python3.6/site-packages/urllib3/util/timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/opt/anaconda/lib/python3.6/site-packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=30, read=30, total=None), but it must be an int, float or None.
```

**Comment by Vitruvia** [comment] 2017-08-07 02:22
That's curious. I have the error on windows but the software works well on my ubuntu 16.04 virtual machine.

**Comment by kylebarron** [comment] 2017-08-08 19:25
It could be something with Anaconda. I'm not sure. I haven't gotten it to work yet.

**Comment by kylebarron** [comment] 2017-08-08 22:49
I'm not sure if this is the issue, but my Dropbox App token doesn't look like the example in the README. It has no dashes, but is the same length as the example *including* dashes. Has the specification for the Dropbox app token changed recently?

**Comment by littleninja** [comment] 2017-08-14 05:52
Same error on MacOS 10.12.6 and Python 2.7.13 :: Anaconda custom (x86_64).

**Comment by anishathalye** [comment] 2017-08-14 17:27
Okay, enough people are having problems that this is probably a bug (either in git-remote-dropbox or the Dropbox SDK or something...)

I haven't been able to reproduce it yet, but I'll try playing around with Anaconda and see if I can get it to break. In the meantime, if anyone can give me details or info on how to reproduce the bug, that would be really helpful.

**Comment by kylebarron** [comment] 2017-08-14 18:23
### Steps to Reproduce:

I created a new Google Cloud instance running Ubuntu 16.04 LTS. 

I then installed the Python 3.6 version of Anaconda:
```bash
wget https://repo.continuum.io/archive/Anaconda3-4.4.0-Linux-x86_64.sh
bash Anaconda3-4.4.0-Linux-x86_64.sh -b -p ~/anaconda
```

Then changed my path:
```bash
export PATH=~/anaconda/bin:$PATH
```

Installed git-remote-dropbox:
```bash
:~$ pip install git-remote-dropbox
Collecting git-remote-dropbox
  Downloading git_remote_dropbox-1.0.1-py2.py3-none-any.whl
Collecting dropbox<9,>=8.0 (from git-remote-dropbox)
  Downloading dropbox-8.0.0-py3-none-any.whl (392kB)
    100% |████████████████████████████████| 399kB 2.1MB/s 
Requirement already satisfied: six>=1.3.0 in ./anaconda/lib/python3.6/site-packages (from dropbox<9,>=8.0->git-remote-dropbox)
Requirement already satisfied: requests!=2.16.0,!=2.16.1,!=2.6.1,>=2.5.1 in ./anaconda/lib/python3.6/site-packages (from dropbox<9,>=8.0->git-remote-dropbox)
Collecting urllib3 (from dropbox<9,>=8.0->git-remote-dropbox)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 3.3MB/s 
Installing collected packages: urllib3, dropbox, git-remote-dropbox
Successfully installed dropbox-8.0.0 git-remote-dropbox-1.0.1 urllib3-1.22
```

Then went to the app console. Selected "Create App" > "Dropbox API" > "Full Dropbox" > Name: "test-new-111" > Choose Dropbox Account: "Personal" (I also have a work Dropbox). Then clicked on "Generate Access Token" and copied and pasted that into `~/.git-remote-dropbox.json`:
```json
{
    "default": "..."
}
```

Then created a test git repo:
```bash
mkdir test
cd test
git init
git remote add origin "dropbox:///path/to/repo"
echo "test" >> README.md
git add README.md
git config --global user.email "barronk@mit.edu"
git config --global user.name "Kyle Barron"
git commit -m "Initial Commit"
```

And then was unable to push:
```bash
~/test$ git push -u origin master
error: unexpected exception (run with -v for details)
~/test$ git push -u origin master -v
Pushing to dropbox:///path/to/repo
Traceback (most recent call last):
  File "/home/kyle/anaconda/lib/python3.6/site-packages/urllib3/util/timeout.py", line 124, in _validate_timeout
    float(value)
TypeError: float() argument must be a string or a number, not 'Timeout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kyle/anaconda/bin/git-remote-dropbox", line 11, in <module>
    sys.exit(main())
  File "/home/kyle/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 759, in main
    helper.run()
  File "/home/kyle/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 370, in run
    self._do_list(line)
  File "/home/kyle/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 395, in _do_list
    refs = self._get_refs(for_push=for_push)
  File "/home/kyle/anaconda/lib/python3.6/site-packages/git_remote_dropbox/__init__.py", line 652, in _get_refs
    res = self._connection().files_list_folder(loc, recursive=True)
  File "/home/kyle/anaconda/lib/python3.6/site-packages/dropbox/base.py", line 715, in files_list_folder
    None,
  File "/home/kyle/anaconda/lib/python3.6/site-packages/dropbox/dropbox.py", line 234, in request
    timeout=timeout)
  File "/home/kyle/anaconda/lib/python3.6/site-packages/dropbox/dropbox.py", line 325, in request_json_string_with_retry
    timeout=timeout)
  File "/home/kyle/anaconda/lib/python3.6/site-packages/dropbox/dropbox.py", line 409, in request_json_string
    timeout=timeout,
  File "/home/kyle/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 565, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/kyle/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/kyle/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/kyle/anaconda/lib/python3.6/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/home/kyle/anaconda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 588, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/home/kyle/anaconda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 303, in _get_timeout
    return Timeout.from_float(timeout)
  File "/home/kyle/anaconda/lib/python3.6/site-packages/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/home/kyle/anaconda/lib/python3.6/site-packages/urllib3/util/timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/home/kyle/anaconda/lib/python3.6/site-packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=30, read=30, total=None), but it must be an int, float or None.
```

**Comment by IcePhoenX** [comment] 2017-08-20 21:33
The [issue](https://github.com/dropbox/dropbox-sdk-python/issues/114) is with the requests library's version that comes with anaconda is incompatible with the current dropbox SDK. It comes with requests 2.14.2 preinstalled, you should update to the latest version.
While the SDK doesn't fix the requirement, @anishathalye could fix this temporarily with adding requests>=2.18.1 to the requirements.

**Comment by anishathalye** [comment] 2017-08-21 02:23
Ooh thanks for figuring this out. [Here](https://github.com/dropbox/dropbox-sdk-python/blob/91d48feac5a04d2d932c8b2165be73845538d528/setup.py#L28) is the relevant line in dropbox-sdk-python. It would be better if it was fixed upstream rather than working around it here. @IcePhoenX would you want to open up an issue in dropbox-sdk-python?

**Comment by anishathalye** [comment] 2017-08-22 07:04
ok nvm I opened an issue

**Comment by anishathalye** [comment] 2017-08-24 18:29
Added a workaround in git-remote-dropbox 1.0.2. Let me know if it works for you?

**Comment by Vitruvia** [comment] 2017-08-24 18:40
It works for me! Thanks!

**Comment by anishathalye** [comment] 2017-08-24 18:40
Awesome! Closing the issue now.

**Closed by anishathalye** 2017-08-24 18:40 UTC
Labels: bug
